-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Port + land
-- monitor=DP-5,1920x1080@144,1080x430,1 #, vrr, 1
-- monitor=HDMI-A-3,1080x1920,0x0,1,transform,1
-- monitor=,preferred,auto,1
-- All Land
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-3",
    mode = "1920x1080@144",
    position = "1920x0",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/
-- Installed wayland/hyprland tools
-- pacman -S waybar swaync j4-dmenu-desktop bemenu ttf-font-awesome

-- Set programs that you use
local terminal = "kitty --start-as=minimized -e tmux"
local fileManager = "dolphin"
-- $menu = bemenu-run
local menu = "j4-dmenu-desktop --dmenu='bemenu -i -c -l 5 down --prompt \"run\" --border 2 --border-radius 15 --bdr \" --#33ccffee\" --margin 24 --hp 24 --width-factor 0.4 --nb \"##3f3f3f\" --nf \"##dcdccc\" --fn \"TTF:FiraCodeNerdFontMono-Regular.ttf 12\" --fb \"##1e1e2e\" --ff \"##cdd6f4\" --nb \"##1e1e2e\" --nf \"##cdd6f4\" --tb \"##1e1e2e\" --hb \"##1e1e2e\" --tf \"##f38ba8\" --hf \"##f9e2af\" --af \"##cdd6f4\" --ab \"##1e1e2e\"'"
--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
-- Set primary monitor
-- Screensharing via hyprland portals
-- Notification daemon
-- Waybar
-- Wallpapers

-- launch applications
-- exec-once = [workspace 3 silent] gtk-launch discord-discord.desktop
-- exec-once = nm-applet &
-- exec-once = waybar & hyprpaper & firefox

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- So dolphin can resolve openwith dialog (KDE weirdness)
hl.env("XDG_MENU_PREFIX", "arch-")
hl.env("XDG_DATA_DIRS", "/usr/share:/usr/local/share:$HOME/.local/share")

-- XDG User DIRS
hl.env("XDG_DESKTOP_DIR", "$HOME/Desktop")
hl.env("XDG_DOWNLOAD_DIR", "$HOME/Downloads")
hl.env("XDG_DOCUMENTS_DIR", "$HOME/Documents")
hl.env("XDG_MUSIC_DIR", "$HOME/Music")
hl.env("XDG_PICTURES_DIR", "$HOME/Pictures")
hl.env("XDG_VIDEOS_DIR", "$HOME/Videos")

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + Z", hl.dsp.window.fullscreen({ action = "toggle" }))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + N", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(mainMod .. " + M", hl.dsp.focus({ workspace = "r+1" }))

hl.bind(mainMod .. " + SHIFT + N", hl.dsp.window.move({ workspace = -1 }))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.window.move({ workspace = "+1" }))

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + O", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.layout("swapsplit"))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.swap({ direction = "d" }))

hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\""))
hl.bind("Print", hl.dsp.exec_cmd("grim"))

hl.bind(mainMod .. " + R", hl.dsp.submap(""))
hl.define_submap("", function()

    hl.bind("H", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
    hl.bind("L", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
    hl.bind("K", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })
    hl.bind("J", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })

    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("CONTROL + c", hl.dsp.submap("reset"))
    hl.bind("catchall", hl.dsp.submap("reset"))
end)

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "DP-3",
    default = true,
})

hl.workspace_rule({
    workspace = "5",
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "DP-3",
})

hl.window_rule({
    match = {
        class = "steam",
    },
    workspace = "4",
    float = false,
})

hl.window_rule({
    match = {
        title = "^()$",
        class = "^(steam)$",
    },
    stay_focused = true,
    min_size = "1 1",
})

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle", --master #dwindle
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 10,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = false,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = false,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        -- Deprecated as of 0.55
        --     pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- You probably want this
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering = false,
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hyprland.org/Configuring/Variables/#input
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        repeat_delay = 300,
        repeat_rate = 50,
        touchpad = {
            natural_scroll = false,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#gestures
    gestures = {
        -- workspace_swipe = false
    },
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
    --###################
    --## KEYBINDINGSS ###
    --###################
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- Vim bindings
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    -- bind = $mainMod, M, exit,
    -- Move focus with mainMod + arrow keys
    -- Switch workspaces with mainMod + [0-9]
    -- bind = $mainMod, 7, workspace, 7
    -- bind = $mainMod, 8, workspace, 8
    -- bind = $mainMod, 9, workspace, 9
    -- bind = $mainMod, 0, workspace, 10
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- bind = $mainMod SHIFT, 7, movetoworkspace, 7
    -- bind = $mainMod SHIFT, 8, movetoworkspace, 8
    -- bind = $mainMod SHIFT, 9, movetoworkspace, 9
    -- bind = $mainMod SHIFT, 0, movetoworkspace, 10
    -- Example special workspace (scratchpad)
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- Master layout binding
    --bind = $mainMod, P, layoutmsg, focusmaster
    --bind = $mainMod, O, layoutmsg, cyclenext
    --bind = $mainMod SHIFT, P, layoutmsg, swapwithmaster
    --# Layout Navigation
    --# 
    --bind = $mainMod SHIFT, h, layoutmsg, orientationleft
    --bind = $mainMod SHIFT, l, layoutmsg, orientationright
    --bind = $mainMod SHIFT, k, layoutmsg, orientationup
    --bind = $mainMod SHIFT, j, layoutmsg, orientationdown
    -- Dwindle layout binding
    -- Layout Navigation
    -- 
    -- Resizing 
    -- bind = $mainMod ALT, H, resizeactive, -50 0
    -- bind = $mainMod ALT, L, resizeactive, 50 0
    -- bind = $mainMod ALT, K, resizeactive, 0 50
    -- bind = $mainMod ALT, J, resizeactive, 0 -50
    -- Additional Tools
    --# Resize Submap 
    -- will start a submap called ""
    -- sets repeatable binds for resizing the active window
    -- Resizing 
    -- use reset to go back to the global submap
    -- will reset the submap, which will return to the global submap
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
    -- Example windowrule v1
    -- windowrule = float, ^(kitty)$
    -- Example windowrule v2
    -- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
    -- windowrule = suppressevent maximize, class:.* # You'll probably like this.
    -- not sure this even works
    -- workspace = name:gaming, monitor:DP-5, default:true
    -- windowrule = workspace 1, class:firefox 
    -- windowrule = workspace 2, class:kitty
    -- windowrule = workspace 3, class:discord 
    -- Steam fixes for hover
})

hl.on("hyprland.start", function()
    hl.exec_cmd("xrandr --output DP-3 --primary")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("swaync")
    hl.exec_cmd("waybar & eww daemon")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("firefox", { workspace = "1 silent" })
    hl.exec_cmd("kitty --start-as=minimized -e tmux -- a -t default", { workspace = "2 silent" })
    hl.exec_cmd("steam", { workspace = "4 silent" })
    hl.exec_cmd("lutris", { workspace = "4 silent" })
    hl.exec_cmd("/home/javonne/Applications/bin/discord", { workspace = "3 silent" })
end)

