
require("config.colors").Configure()

require("config.dap").Configure()
require("config.flutter-lsp").Configure()
-- require("config.fugitive").Configure()
require("config.galaxyline").Configure()
-- require("config.harpoon").Configure()
require("config.lsp").Configure()
require("config.mason-lsp").Configure()
require("config.neo-tree").Configure()
-- require("config.tabby").Configure()
require("config.telescope").Configure()
require("config.treesitter").Configure()
require("config.undotree").Configure()

require("config.silicon").Configure()
require("config.diagnostics").Configure()
-- config.ConfigureColours()
-- config.ConfigureGalaxyLine()
-- config.ConfigureTreeSitter()
-- config.ConfigureLSPZero()
-- config.ConfigureMasonLSP()
-- config.ConfigureDAP()
-- config.ConfigureUndoTree()
-- config.ConfigureNeoTree()
-- config.ConfigureTelescope()
-- config.ConfigureGalaxyLine()
-- -- ConfigureTabby()
-- -- ConfigureFugitive()
-- -- ConfigureHarpoon()
-- config.ConfigureFlutterLSP()
